version: '3.3'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'ohana'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root-api'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql-api8
    network_mode: "host"  

  app: 
    image: rodrigoparede/api
    restart: always
    ports: 
      - '8080:8080'
    expose: 
      - '8080'
    network_mode: "host"
    depends_on:
      - db
  

volumes:
  my-db:
